services:
  application:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    command: make run
    container_name: punish-bot
    restart: unless-stopped
    tty: true
    volumes:
      - ./.env:/app/.env
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
