name: Docker build and execute tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: asia-northeast1-docker.pkg.dev
          tags: |
            type=semver,pattern={{raw}} # tag を利用
            type=sha,format=short       # sha を利用

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: github-actions/docker-build-cache
          push: false
          tags: ${{ steps.metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max # 全レイヤーキャッシュ
